<?xml version="1.0"?>
<package format="2">
  <name>voxblox_map</name>
  <version>0.0.0</version>
  <description>Voxblox map</description>

  <maintainer email="yuepan@student.ethz.ch">Yue Pan</maintainer>

  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <buildtool_depend>catkin_simple</buildtool_depend>

  <depend>cv_bridge</depend>
  <depend>gflags_catkin</depend>
  <depend>interactive_markers</depend>
  <depend>minkindr_conversions</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_ros</depend>
  <depend>sensor_msgs</depend>
  <depend>tf</depend>
  <depend>voxblox</depend>
  <depend>voxblox_ros</depend>
  <depend>voxblox_msgs</depend>
  <depend>voxblox_rviz_plugin</depend>
</package>
